### ISSUE TITLE
请问Loading图如何修改

### ISSUE THREAD

**Issue by ghost** [Ovilia/blog#11]
您好，网站十分漂亮，我fork您做了一个，有个问题向您请教：
比如 http://zhangwenli.com/ 的Loading Gif图我想换成其他的，该如何修改？具体应该修改哪些文件？
麻烦您了，忘回答。

**Comment by Ovilia** [comment]
修改下 `img` 下的 `loading.gif` 就行了

**Comment by ghost** [comment]
您好，谢谢您的回复，我已经修改了*loading.gif*, 但是主页并未改变，麻烦您再帮我看一下：

[我的主页](http://xresearcher.com/), 
[GitHub源代码](https://github.com/well007/blog)

**Comment by Ovilia** [comment]
我看到的已经变了，你那边应该是缓存

**Comment by ghost** [comment]
您好，问题仍然没有解决，让朋友浏览了一下，还是没变，我也清理过缓存了。
目前显示仍和您的主页一致，冒昧再问一下，你看到的是这样的吗？
[想要的效果](https://github.com/well007/blog/blob/gh-pages/img/loading.gif)
[我的主页](http://xresearcher.com/)

请您看到回复一下是否已正常？
感谢！

**Comment by Ovilia** [comment]
`loading.gif` 是在图片加载前显示的图片（写了 `<img src="xxxxx/loading.gif" data-src="...">` 这样形式的图片，加载前显示 `loading.gif`，加载完显示实际的图片，也就是 `data-src` 里的），跟 `zhangwenli.com` 首页的图是没有关系的。后者是 SVG 动画做的，代码在 https://github.com/Ovilia/ovilia.github.io/blob/master/index.jade#L36

**Comment by ghost** [comment]
谢谢您的回答，我是计算机小白，对这个还不是很懂，至于SVG动画我查资料再学习，home页的布局我再学一些HTML教程。
您的耐心回答，十分感谢！
