### ISSUE TITLE
Popover for password still visible even I choose to post as guest.

### ISSUE THREAD

**Issue by jianjunz** [Ovilia/blog#2]
Steps to reproduce the issue:
1. Add a comment to a post without login.
2. Leave name, email and password blank.
3. Click submit button
4. Select "I'd rather post as guest"

Expected outcome:
Both textbox and popover for password are hidden.

Actual outcome:
Popover for password still visible.

Attachment:
![20140816222311](https://cloud.githubusercontent.com/assets/2958054/3942046/6a04292a-2551-11e4-986c-c0cb513746aa.png)

**Comment by Ovilia** [comment]
@LittleLittle Thanks for your report! But it seems to be the bug of http://disqus.com , which is a comment plugin I use. It seems to be nothing I can do with it...
