### ISSUE TITLE
Fixed music panel sometimes moves to strange positions

### ISSUE THREAD

**Issue by Ovilia** [Ovilia/blog#5]
This problem appears only on Chrome in Windows. Seems WebKit hasn't update the new position of fixed element when scroll event triggered.

**Comment by Ovilia** [comment]
As explained in http://stackoverflow.com/questions/11258877/fixed-element-disappears-in-chrome#answer-25922011 , this seems to be a bug of WebKit that

> it seems to be a bug that occurs when there is too much going on inside the page

Use `transform: translateZ(0); -webkit-transform: translateZ(0);` to force using GPU.

**Comment by wuciawe** [comment]
awesome
